#ifdef UNCHECKED_PRODUCTION_BUILD
#define _CHOOSE_OVERLOAD2(_1, _2, _OVERLOAD, ...) _OVERLOAD
#define _CHOOSE_OVERLOAD3(_1, _2, _3, _OVERLOAD, ...) _OVERLOAD

#define _IGNORE1(cond) 
#define _IGNORE2(cond, msg) 
#define _IGNORE3(a, b, c) 

#define IN_DEVELOPMENT_ONLY(fn)
#define ASSERT_NOT_REACHED()

#define ASSERT(...) _CHOOSE_OVERLOAD2(__VA_ARGS__, _IGNORE2, _IGNORE1)(__VA_ARGS__)
#define ASSERT_IS_INT(...) _CHOOSE_OVERLOAD2(__VA_ARGS__, _IGNORE2, _IGNORE1)(__VA_ARGS__)
#define ASSERT_IS_INT_IN_RANGE(...) _CHOOSE_OVERLOAD3(__VA_ARGS__, _IGNORE3, _IGNORE2)(__VA_ARGS__)
#define ASSERT_IS_NON_NEGATIVE_INT(...) _CHOOSE_OVERLOAD2(__VA_ARGS__, _IGNORE2, _IGNORE1)(__VA_ARGS__)
#define ASSERT_IS_POSITIVE_INT(...) _CHOOSE_OVERLOAD2(__VA_ARGS__, _IGNORE2, _IGNORE1)(__VA_ARGS__)
#define ASSERT_IS_ARRAY(...) _CHOOSE_OVERLOAD2(__VA_ARGS__, _IGNORE2, _IGNORE1)(__VA_ARGS__)
#define ASSERT_IS_FUNC(...) _CHOOSE_OVERLOAD2(__VA_ARGS__, _IGNORE2, _IGNORE1)(__VA_ARGS__)
#define ASSERT_IS_STRING(...) _CHOOSE_OVERLOAD2(__VA_ARGS__, _IGNORE2, _IGNORE1)(__VA_ARGS__)
#define ASSERT_IS_NUM(...) _CHOOSE_OVERLOAD2(__VA_ARGS__, _IGNORE2, _IGNORE1)(__VA_ARGS__)
#define ASSERT_IS_UNDEF(...) _CHOOSE_OVERLOAD2(__VA_ARGS__, _IGNORE2, _IGNORE1)(__VA_ARGS__)
#define ASSERT_IS_OBJ(...) _CHOOSE_OVERLOAD2(__VA_ARGS__, _IGNORE2, _IGNORE1)(__VA_ARGS__)
#define ASSERT_IS_CTOR(...) _CHOOSE_OVERLOAD3(__VA_ARGS__, _IGNORE3, _IGNORE2)(__VA_ARGS__)
#endif
